const restaurantNames = [
  "Cornish Pastry CO",
  "Fast Breaks Restaurant",
  "Gaskins Cabin Restaurant",
  "Zio's New York Style Pizzeria",
  "Gambardella's Pasta Bella",
  "LA Sandwicherie",
  "Connolly's Pub & Restaurant",
  "Chompie's NY Kosher Style",
  "Pepperoni's Tavern",
  "Brasa Grill Brazilian Steak",
  "Jans & Tony's Pizza",
  "Rainbow Grille & Tavern",
  "Josephine's Ristorante",
  "Bill's Restaurant",
  "Summit Hickory Pit Bbq",
  "Pepperonis",
  "Brooklyn Pizza",
  "DO North Pizza",
  "Down The Hatch Restaurant",
  "Abercrombie Seafood Grill",
  "Rustic Kitchen",
  "Circle B Chuckwagon",
  "LA Sardine",
  "Shiv Shakti Inc",
  "Front Street Grill",
  "Ho Wan Chinese Restaurant",
  "Andy's Restaurants Inc",
  "Continental Flambe",
  "Brooks Tavern",
  "Bar J Chuckwagon Suppers",
  "Manchester NY Inc",
  "Bayard's",
  "Jennie Rae's Llc",
  "Ron's Island Grill",
  "Flaming Amy's Burrito",
  "Sofie's Bistro",
  "Cafe In The Court",
  "Glen Burnie Checkers",
  "B J Pumpernickel's",
  "Tom Tom Asian Grill",
  "Finnigan's",
  "Werry's Cottages Motel & Pub",
  "George's Pastaria & Devine",
  "Los Gauchitos Pizzeria",
  "Colonial Restaurant",
  "Cafe Mezzanotte",
  "Jack's Restaurant",
  "House Of Wing",
  "Vki Japanese Restaurant",
  "5 O'Clock Club"
]; //50

const names = [
  "Mel Mccartney",
  "Fatimah Fit",
  "Le Leavens",
  "Lynetta Llewellyn",
  "Florencia Faison",
  "Kylie Kimberlin",
  "Lavenia Lanham",
  "Lesia Leger",
  "Loura Lauria",
  "Mariella Miser",
  "Karan Kiser",
  "Arletha Atwell",
  "Susana Sumlin",
  "Jacquelin Jeanlouis",
  "Yen Yamashiro",
  "Gerald Goins",
  "Pearl Ponds",
  "Nada Nies",
  "Marilu Mcclusky",
  "Sal Sharman",
  "Chris Farely",
  "Rafe",
  "Hammertime"
]; //23



const dates = [
'March 25, 2000',
'November 8, 2000',
'January 18, 2001',
'February 28, 2001',
'June 19, 2001',
'June 27, 2002',
'April 25, 2003',
'July 11, 2003',
'May 6, 2004',
'July 23, 2004',
'January 4, 2006',
'August 12, 2006',
'April 28, 2007',
'May 24, 2009',
'July 6, 2009',
'May 4, 2011',
'May 25, 2011',
'October 18, 2011',
'March 18, 2012',
'August 12, 2012',
'February 1, 2014',
'January 17, 2015',
'March 24, 2018',
'September 9, 2018',
'January 13, 2019',
]; //25

const pictures = [
  'https://vice-images.vice.com/images/content-images/2015/10/16/if-you-smell-what-the-rock-is-cooking-101-body-image-1444992411.jpg?output-quality=75',
  'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/25551832_10155567967329807_1706534759487628152_n.jpg?_nc_cat=1&_nc_ht=scontent-sjc3-1.xx&oh=7ff0683712fbedac7ff26644b91b94bc&oe=5D7001B6',
  'https://static.boredpanda.com/blog/wp-content/uploads/2017/03/funny-cristiano-ronaldo-statue-fail-33-58dcc00c785ef__700.jpg',
  'https://akns-images.eonline.com/eol_images/Entire_Site/2019112/rs_600x600-190212175714-600-jessica-simpson-pregnant2.cl.021219.jpg?fit=around|700:700&crop=700:700;center,top&output-quality=90',
  'https://uproxx.files.wordpress.com/2018/12/giannispunch.jpg?w=650',
  'https://static.businessinsider.com/image/59bc1340248849771e74b4be-750.jpg',
  'https://www.thefamouspeople.com/profiles/thumbs/chris-farley-2.jpg',
  'https://cdn2.atlantamagazine.com/wp-content/uploads/sites/4/2017/05/0617_NeilDegrasseTyson_Gluekit_oneuseonly.jpg',
  'https://www.thewrap.com/wp-content/uploads/2018/04/Princess-Bride-Andre-the-Giant-1.jpg',
  'https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1439,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1492107336/articles/2016/11/08/the-uncompromising-politics-of-dave-chappelle/161107-Zimmerman-black-bush-tease_fhfoc9',
  'https://media.vanityfair.com/photos/59a589d562a7f43bf00ac4cd/master/pass/disgust-incest-daenerys.jpg'
]; //11

const reviews = [
  'This, hands down, is the worst restaurant Ive been too in like my entire life. I got there and it was empty. I don\'t mean no customers, I mean no staff. They had gone out for the night so I decided to just help myself. In all honesty, the food was good. And free so I guess I give them a solid 3 stars. Why not.',
  'The ramen tastes like it is out of instant ramen package. The shave ice they give out for free is not bad. But it seems more like it is a $15 shave ice with ramen instead of $15 ramen with shave ice',
  'Bad service, bad food, handsome owner, total score 3.5',
  'the owner mugged me',
  'The best stir fry ong choy around town with ample amount of garlic. Under $10. The best deal when you have the craving',
  'The ramen tastes like it is out of instant ramen package. The shave ice they give out for free is not bad. But it seems more like it is a $15 shave ice with ramen instead of $15 ramen with shave ice',
  'If you are craving a burger with toasted bun,  homemade hamburger patty, and unlimited fries, this is heaven',
  'The best poke bowl around town hands down. Nested in a dirty Chinatown market but the owner is Japanese so they are super clean. The taste is different than the conventional supermarket poke bowl you get that is heavy on the seasoning. The fish they got is directly from the market.',
  'Stone Kitchen is at Embarcadaro center is Absolutely Terrible. They serve frozen hamburger and they BURNT IT T.T I can taste the bitterness in all my bites. Start worrying about cancer....',
  'Their dim sum isn\'t bad BUT you have to have them make it fresh otherwise it is over-steamed.',
  'The best chai latte ever. They uses a special blend of spices. A world different than Starbucks',
  'This Thai lady that runs this food truck gives a lot of food. Their Pad Kee Mow is amazing. I eat there everyday.',
  'I bought a $7.49 have ice and got a $74.9 bill at this shave ice shop. Not sure if they are trying to scam me. The lady didn\'t say sorry.',
  'On my way to this burger place on the bus one guy was handing out roses to the bus riders. I took one and decided to give it to the waitress, and she told me "I will for sure give you my number" >.< The burger is really good. $5 monday burger night yummmmm. Oh she is hot too ~~~~',
  'On the steak tartare: The initial flavor was bland, quickly followed by a fetid, ammonia-like tang. It was an aroma that recalled room-temperature hamburger meat from a grocer that lost power. I felt my eyes water up as I chewed. I tried to swallow but even gravity couldn\'t keep it down.',
  'Being the trend follower that I am, I gave in and dished out the $350 for this plated menu. After reading the recent reviews in The Anaconda Standard while passing through Montana about this #1 rated restaurant in the entire city of Cleavland, Ohio, which we all know is a town of culinary expertise, I booked a table immediately. Holy...amazing. The Lebron jerseys along every wall truly set a romantic mood, only to be topped off by the sweet sounds of the local highschool\'s recent talent show winners "Boys 2 Boyz". The food, delicious. Three words: Kraft Singles Heaven. Don\'t even get me started on the dessert, okay, you got me, fried twinkies. Get yourself on the 3 month waiting list, worth every penny.',
  'Best I ever had -Me (Not Drake)'
]; //17

module.exports = {
  restaurantNames, 
  names,
  dates,
  pictures,
  reviews
}